/**
 * with-screentime/consume-app-group.ts
 *
 * Reads (does NOT modify) feature 014's App Group configuration and
 * attaches the same App Group entitlement to the new monitor extension
 * target so the extension can read the persisted selection token.
 *
 * Detection: the presence of `native/ios/widgets/AppGroupKeys.swift` (the
 * marker file shipped by feature 014) is treated as the signal. When the
 * marker is absent, we log a prebuild warning and continue without
 * attaching the App Group — the host app still functions; only the
 * monitor extension loses cross-process state.
 *
 * The suite name is computed identically to feature 014's
 * `add-app-group.ts` (`group.<bundleId>.showcase`) so the two features
 * point at the same UserDefaults suite.
 */

import { type ConfigPlugin, IOSConfig, withDangerousMod } from '@expo/config-plugins';
import * as fs from 'fs';
import * as path from 'path';

const APP_GROUPS_KEY = 'com.apple.security.application-groups';
const MARKER_REL = path.join('native', 'ios', 'widgets', 'AppGroupKeys.swift');

function suiteFor(bundleId: string): string {
  return `group.${bundleId}.showcase`;
}

/**
 * Pure detection helper — exposed for unit tests.
 * Returns the App Group suite name when the feature 014 marker file is
 * present, or `null` otherwise.
 */
export function detectAppGroupSuite(projectRoot: string, bundleId: string): string | null {
  const markerPath = path.join(projectRoot, MARKER_REL);
  if (!fs.existsSync(markerPath)) return null;
  return suiteFor(bundleId);
}

export const withScreenTimeAppGroup: ConfigPlugin = (config) => {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const bundleId = IOSConfig.BundleIdentifier.getBundleIdentifier(cfg) ?? 'com.example.spot';
      const suite = detectAppGroupSuite(cfg.modRequest.projectRoot, bundleId);
      if (suite === null) {
        // Marker missing — log a warning so the developer knows the monitor
        // extension will run without cross-process state. This is FR-021's
        // "consume only" guarantee in action: we never write to feature 014.
        // eslint-disable-next-line no-console
        console.warn(
          '[with-screentime] feature 014 App Group marker not found at ' +
            MARKER_REL +
            ' — monitor extension will not share UserDefaults with the host app.',
        );
        return cfg;
      }

      // Write a sidecar entitlements file for the monitor extension target
      // alongside the Swift sources. The Xcode project generated by Expo
      // prebuild references it from the SpotScreenTimeMonitor target via
      // the build setting added in add-monitor-extension.ts.
      const entitlementsDir = path.join(cfg.modRequest.projectRoot, 'native/ios/screentime');
      if (!fs.existsSync(entitlementsDir)) {
        fs.mkdirSync(entitlementsDir, { recursive: true });
      }
      const entitlementsPath = path.join(entitlementsDir, 'SpotScreenTimeMonitor.entitlements');
      const plist =
        '<?xml version="1.0" encoding="UTF-8"?>\n' +
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n' +
        '<plist version="1.0">\n' +
        '<dict>\n' +
        `\t<key>${APP_GROUPS_KEY}</key>\n` +
        '\t<array>\n' +
        `\t\t<string>${suite}</string>\n` +
        '\t</array>\n' +
        '</dict>\n' +
        '</plist>\n';
      const existing = fs.existsSync(entitlementsPath)
        ? fs.readFileSync(entitlementsPath, 'utf8')
        : null;
      if (existing !== plist) {
        fs.writeFileSync(entitlementsPath, plist, 'utf8');
      }
      return cfg;
    },
  ]);
};

export default withScreenTimeAppGroup;
